name: "Minecraft Bedrock Servers"
version: "1.0.0"
slug: "mcbedrock"
description: "Bedrock server via itzg image"
arch:
  - aarch64
startup: services
boot: auto
ports:
  19132/udp: 19132
image: "itzg/minecraft-bedrock-server:latest"

# Static environment (edit these values here, no UI templating)
environment:
  TZ: "Asia/Singapore"
  SERVER_NAME: "My Bedrock on HA"
  GAMEMODE: "survival"
  DIFFICULTY: "normal"
  LEVEL_NAME: "world"
  MAX_PLAYERS: "10"
  ONLINE_MODE: "true"
  WHITE_LIST: "false"
