name: "Minecraft Bedrock Server"
version: "1.0.0"
slug: "mcbedrock"
description: "Bedrock server via itzg image"
arch:
  - aarch64
startup: services
boot: auto
ports:
  19132/udp: 19132
image: "itzg/minecraft-bedrock-server:latest"
