name: "Minecraft Bedrock Server"
version: "1.0.0"
slug: "mcbedrock"
description: "Minecraft Bedrock Server running inside Home Assistant OS"
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
ports:
  19132/udp: 19132
image: "itzg/minecraft-bedrock-server:latest"
